"""集中定数定義。

GUI/再文字起こしパイプラインで散在していたマジック文字列・数値をここに集約し、
将来の調整時に漏れを防ぐ目的。
"""
from __future__ import annotations

# 利用可能な Whisper 公式モデル名一覧 (UI コンボボックス用)
WHISPER_MODELS: list[str] = [
    "large-v3",
    "distil-large-v3",
]

# プレースホルダ表示用テキスト
PLACEHOLDER_PENDING = "[再解析中]"

# ウォッチドッグタイムアウト (ms)
DEFAULT_WATCHDOG_TIMEOUT_MS = 15000

# 重複テキスト自動マージ用閾値 (デバッグ/品質向上)
# 直前セグメントと JA/RU 両テキストが完全一致し、区間長がこの値未満ならマージ候補
DUP_MERGE_MAX_SEG_DUR = 1.20  # 秒
# 直前セグメント終端と今回セグメント開始のギャップ許容 (通常 0 か極小)
DUP_MERGE_MAX_GAP = 0.30      # 秒

# 部分再文字起こしの最大許容長 (秒)
MAX_RANGE_SEC = 30.0

# モデルキャッシュ上限 (LRU)
DEFAULT_MODEL_CACHE_LIMIT = 2

# 無音区間の最小長さ (秒: 転写結果に無音セグメントを挿入する境界)
SILENCE_MIN_GAP = 0.5

# faster-whisper が対応する言語コード → 英語名マッピング
WHISPER_LANGUAGES: dict[str, str] = {
    "af": "Afrikaans",
    "am": "Amharic",
    "ar": "Arabic",
    "as": "Assamese",
    "az": "Azerbaijani",
    "ba": "Bashkir",
    "be": "Belarusian",
    "bg": "Bulgarian",
    "bn": "Bengali",
    "bo": "Tibetan",
    "br": "Breton",
    "bs": "Bosnian",
    "ca": "Catalan",
    "cs": "Czech",
    "cy": "Welsh",
    "da": "Danish",
    "de": "German",
    "el": "Greek",
    "en": "English",
    "es": "Spanish",
    "et": "Estonian",
    "eu": "Basque",
    "fa": "Persian",
    "fi": "Finnish",
    "fo": "Faroese",
    "fr": "French",
    "gl": "Galician",
    "gu": "Gujarati",
    "ha": "Hausa",
    "haw": "Hawaiian",
    "he": "Hebrew",
    "hi": "Hindi",
    "hr": "Croatian",
    "ht": "Haitian Creole",
    "hu": "Hungarian",
    "hy": "Armenian",
    "id": "Indonesian",
    "is": "Icelandic",
    "it": "Italian",
    "ja": "Japanese",
    "jw": "Javanese",
    "ka": "Georgian",
    "kk": "Kazakh",
    "km": "Khmer",
    "kn": "Kannada",
    "ko": "Korean",
    "la": "Latin",
    "lb": "Luxembourgish",
    "ln": "Lingala",
    "lo": "Lao",
    "lt": "Lithuanian",
    "lv": "Latvian",
    "mg": "Malagasy",
    "mi": "Maori",
    "mk": "Macedonian",
    "ml": "Malayalam",
    "mn": "Mongolian",
    "mr": "Marathi",
    "ms": "Malay",
    "mt": "Maltese",
    "my": "Myanmar",
    "ne": "Nepali",
    "nl": "Dutch",
    "nn": "Nynorsk",
    "no": "Norwegian",
    "oc": "Occitan",
    "pa": "Punjabi",
    "pl": "Polish",
    "ps": "Pashto",
    "pt": "Portuguese",
    "ro": "Romanian",
    "ru": "Russian",
    "sa": "Sanskrit",
    "sd": "Sindhi",
    "si": "Sinhala",
    "sk": "Slovak",
    "sl": "Slovenian",
    "sn": "Shona",
    "so": "Somali",
    "sq": "Albanian",
    "sr": "Serbian",
    "su": "Sundanese",
    "sv": "Swedish",
    "sw": "Swahili",
    "ta": "Tamil",
    "te": "Telugu",
    "tg": "Tajik",
    "th": "Thai",
    "tk": "Turkmen",
    "tl": "Tagalog",
    "tr": "Turkish",
    "tt": "Tatar",
    "uk": "Ukrainian",
    "ur": "Urdu",
    "uz": "Uzbek",
    "vi": "Vietnamese",
    "yi": "Yiddish",
    "yo": "Yoruba",
    "yue": "Cantonese",
    "zh": "Chinese",
}

# faster-whisper が対応する言語コード → 日本語名マッピング
WHISPER_LANGUAGES_JA: dict[str, str] = {
    "af": "アフリカーンス語",
    "am": "アムハラ語",
    "ar": "アラビア語",
    "as": "アッサム語",
    "az": "アゼルバイジャン語",
    "ba": "バシキール語",
    "be": "ベラルーシ語",
    "bg": "ブルガリア語",
    "bn": "ベンガル語",
    "bo": "チベット語",
    "br": "ブルトン語",
    "bs": "ボスニア語",
    "ca": "カタルーニャ語",
    "cs": "チェコ語",
    "cy": "ウェールズ語",
    "da": "デンマーク語",
    "de": "ドイツ語",
    "el": "ギリシャ語",
    "en": "英語",
    "es": "スペイン語",
    "et": "エストニア語",
    "eu": "バスク語",
    "fa": "ペルシャ語",
    "fi": "フィンランド語",
    "fo": "フェロー語",
    "fr": "フランス語",
    "gl": "ガリシア語",
    "gu": "グジャラート語",
    "ha": "ハウサ語",
    "haw": "ハワイ語",
    "he": "ヘブライ語",
    "hi": "ヒンディー語",
    "hr": "クロアチア語",
    "ht": "ハイチ・クレオール語",
    "hu": "ハンガリー語",
    "hy": "アルメニア語",
    "id": "インドネシア語",
    "is": "アイスランド語",
    "it": "イタリア語",
    "ja": "日本語",
    "jw": "ジャワ語",
    "ka": "ジョージア語",
    "kk": "カザフ語",
    "km": "クメール語",
    "kn": "カンナダ語",
    "ko": "韓国語",
    "la": "ラテン語",
    "lb": "ルクセンブルク語",
    "ln": "リンガラ語",
    "lo": "ラオ語",
    "lt": "リトアニア語",
    "lv": "ラトビア語",
    "mg": "マダガスカル語",
    "mi": "マオリ語",
    "mk": "マケドニア語",
    "ml": "マラヤーラム語",
    "mn": "モンゴル語",
    "mr": "マラーティー語",
    "ms": "マレー語",
    "mt": "マルタ語",
    "my": "ミャンマー語",
    "ne": "ネパール語",
    "nl": "オランダ語",
    "nn": "ニーノシュク語",
    "no": "ノルウェー語",
    "oc": "オック語",
    "pa": "パンジャブ語",
    "pl": "ポーランド語",
    "ps": "パシュトー語",
    "pt": "ポルトガル語",
    "ro": "ルーマニア語",
    "ru": "ロシア語",
    "sa": "サンスクリット語",
    "sd": "シンド語",
    "si": "シンハラ語",
    "sk": "スロバキア語",
    "sl": "スロベニア語",
    "sn": "ショナ語",
    "so": "ソマリ語",
    "sq": "アルバニア語",
    "sr": "セルビア語",
    "su": "スンダ語",
    "sv": "スウェーデン語",
    "sw": "スワヒリ語",
    "ta": "タミル語",
    "te": "テルグ語",
    "tg": "タジク語",
    "th": "タイ語",
    "tk": "トルクメン語",
    "tl": "タガログ語",
    "tr": "トルコ語",
    "tt": "タタール語",
    "uk": "ウクライナ語",
    "ur": "ウルドゥー語",
    "uz": "ウズベク語",
    "vi": "ベトナム語",
    "yi": "イディッシュ語",
    "yo": "ヨルバ語",
    "yue": "広東語",
    "zh": "中国語",
}

# スクリプト（文字体系）関連のデータは廃止されました。
# 以前は Unicode スクリプトに基づく言語補強を行っていましたが、
# 誤検出や過剰補正を招くため機能を削除しています。

__all__ = [
    "WHISPER_MODELS",
    "WHISPER_LANGUAGES",
    "WHISPER_LANGUAGES_JA",
    # script-related constants removed
    "PLACEHOLDER_PENDING",
    "DEFAULT_WATCHDOG_TIMEOUT_MS",
    "DUP_MERGE_MAX_SEG_DUR",
    "DUP_MERGE_MAX_GAP",
    "MAX_RANGE_SEC",
    "DEFAULT_MODEL_CACHE_LIMIT",
]
